### ISSUE TITLE
Page should have the following banners/sections

### ISSUE THREAD

**Issue by franznoel** [fritzdenim/pangMoves#11]
Change the banners/sections on these pages: 
**Banner 1 and Banner 3**
- http://moviefund.com/profile/
- http://moviefund.com/for-investors/

Team banner (grab from homepage / admin)
- http://moviefund.com/members/

**Banner 2 and Banner 3**
- http://moviefund.com/movie-fund-page/

**Banner 4 and Banner 2**
- http://moviefund.com/movies/
- http://moviefund.com/how-it-works/

**Banner 4**
- http://moviefund.com/for-film-makers/
- http://moviefund.com/faqs/

**Banner 1**
- http://moviefund.com/about/

**Banner 3**
- http://moviefund.com/team_patrners/
- http://moviefund.com/movienews/

**No Banners**
- http://moviefund.com/contact-us/
- http://moviefund.com/featured-planetx/

Here are the images: 
Banner 1
![banner1](https://cloud.githubusercontent.com/assets/464229/12671281/5106e01a-c623-11e5-8c1c-ac35dffba0fa.png)

Banner 2
![banner2](https://cloud.githubusercontent.com/assets/464229/12671282/5108cf4c-c623-11e5-95e2-7d44f2e75cf1.png)

Banner 3
![banner3](https://cloud.githubusercontent.com/assets/464229/12671283/510fdad0-c623-11e5-9574-e5d1e6ebf791.png)

Banner 4
![banner4](https://cloud.githubusercontent.com/assets/464229/12671284/5120681e-c623-11e5-85e5-08235f4ca18f.png)

**Comment by franznoel** [comment]
Reporting status of the pages: 
**Done**
- http://moviefund.com/profile/ - done
- http://moviefund.com/members/ - done
- http://moviefund.com/movies/ - done
- http://moviefund.com/how-it-works/ - done
- http://moviefund.com/for-investors/ - done
- http://moviefund.com/for-film-makers/ - done
- http://moviefund.com/faqs/ - done
- http://moviefund.com/about/ - done
- http://moviefund.com/movienews/ - done
- http://moviefund.com/contact-us/ - done
- http://moviefund.com/featured-planetx/ - done
- http://moviefund.com/movie-fund-page/ - done

**Banner 3** (social)
- http://moviefund.com/team_patrners/ - in progress

**Comment by MovieFund** [comment]
Great work 
we probly delete top banner from /movies and just have the blue banner then all the movies and pls delete all the search bits above movies. great work

**Comment by franznoel** [comment]
Everything is done now. 

Just one note: I have changed
http://moviefund.com/team_patrners/
to 
http://moviefund.com/team-partners/ - done
