### ISSUE TITLE
Create a new post type named "featured"

### ISSUE THREAD

**Issue by franznoel** [fritzdenim/pangMoves#14]
Create a new post type named featured. The featured page will compose of all the featured projects.

**Comment by franznoel** [comment]
Make sure that "featured-planetx" will not redirect from "featured"

**Comment by MovieFund** [comment]
taking a look now mate

**Comment by franznoel** [comment]
Do we need to remove http://moviefund.com/featured-planetx/
since http://moviefund.com/featured/planet-x-gold-of-the-gods/ now works?
