### ISSUE TITLE
Button top

### ISSUE THREAD

**Issue by MovieFund** [fritzdenim/pangMoves#3]
![screen shot 2016-01-27 at 12 47 16 am](https://cloud.githubusercontent.com/assets/16911000/12608222/9b1096e6-c48f-11e5-8e92-3fe71cd0093e.png)

This needs to go to: http://moviefund.com/profile/

**Comment by franznoel** [comment]
Changed the link of UPLOAD PROJECT to point to http://moviefund.com/profile/
