### ISSUE TITLE
Update button names on general pages (not homepage)

### ISSUE THREAD

**Issue by MovieFund** [fritzdenim/pangMoves#4]
Change the "Login/Register" and "Create a Campaign" 
to 
"INVEST NOW" and "UPLOAD A PROJECT"

Found in the following pages:
- [profile](http://moviefund.com/profile/)
- [how it works](http://moviefund.com/how-it-works/)

Not applicable in the following pages: 
- [home](http://moviefund.com/)
- [movies](http://moviefund.com/movies/)
- [faqs](http://moviefund.com/faqs/)
- [about](http://moviefund.com/about/)
- [contact](http://moviefund.com/contact/)

![screen shot 2016-01-27 at 12 49 05 am](https://cloud.githubusercontent.com/assets/16911000/12608246/d3a5ebaa-c48f-11e5-857b-3a8991b4e1b5.png)

**Comment by franznoel** [comment]
Do you mean the buttons "Login/Register" and "Create a Campaign"?

**Comment by MovieFund** [comment]
Yes these buttons need to say INVEST NOW and UPLOAD A PROJECT

**Comment by franznoel** [comment]
I have updated the main description above. Can you verify?

**Comment by franznoel** [comment]
Confirmed that it is working, by Tim.

**Comment by MovieFund** [comment]
Awesome. I've got a guy to help us tranfwe it to my site with lots of
traffic but I kinda of like it on moviefund.com and not themoviefund.com

On Thursday, February 4, 2016, Franz Noel notifications@github.com wrote:

> Closed #4 https://github.com/fritzdenim/pangMoves/issues/4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fritzdenim/pangMoves/issues/4#event-540274482.

## 

Sent from HTC turbo.
