### ISSUE TITLE
Go to contact page

### ISSUE THREAD

**Issue by MovieFund** [fritzdenim/pangMoves#5]
![screen shot 2016-01-27 at 12 49 51 am](https://cloud.githubusercontent.com/assets/16911000/12608258/e8234226-c48f-11e5-8ddb-4f6e154b2785.png)

GOES TO: http://moviefund.com/contact-us/

**Comment by franznoel** [comment]
INVEST NOW link, now goes to: 
http://moviefund.com/contact-us/
