### ISSUE TITLE
Contact forms.

### ISSUE THREAD

**Issue by MovieFund** [fritzdenim/pangMoves#6]
![screen shot 2016-01-27 at 12 50 57 am](https://cloud.githubusercontent.com/assets/16911000/12608276/0f9582b0-c490-11e5-8b41-e5132921ef7c.png)
![screen shot 2016-01-27 at 12 50 51 am](https://cloud.githubusercontent.com/assets/16911000/12608277/0f96d156-c490-11e5-95e6-9ef7441b38ff.png)

and contact form on hompage. Please. Thanks

The contact pages go to: movieinvestors@gmail.com

**Comment by franznoel** [comment]
Tested and check if the information sends data. Verified by Tim.
