### ISSUE TITLE
Social Buttons.

### ISSUE THREAD

**Issue by MovieFund** [fritzdenim/pangMoves#7]
![screen shot 2016-01-27 at 12 53 51 am](https://cloud.githubusercontent.com/assets/16911000/12608336/75035352-c490-11e5-8d34-b49b83e12272.png)

Compare the icons above and below. The icons above, should have black text logos when hovered.
![social icon2](https://cloud.githubusercontent.com/assets/16911000/12608454/154abc88-c491-11e5-87ec-44ec0a20f449.png)

**Comment by MovieFund** [comment]
Please can we replace current social buttons to these...

**Comment by franznoel** [comment]
Need more clarification: So, when the icon is hovered, the logo will change to black?

**Comment by MovieFund** [comment]
Yer from the white ones to the black would be great. They going to look amazing.

**Comment by franznoel** [comment]
Was able to change Social Buttons.
