### ISSUE TITLE
Can we fix this top Banner.

### ISSUE THREAD

**Issue by MovieFund** [fritzdenim/pangMoves#8]
![screen shot 2016-01-27 at 1 07 26 am](https://cloud.githubusercontent.com/assets/16911000/12608688/62c49906-c492-11e5-9ac1-d7d5cd48850b.png)
![screen shot 2016-01-27 at 1 07 26 am](https://cloud.githubusercontent.com/assets/16911000/12608704/7e84e308-c492-11e5-9d21-e5acc90bab81.png)

Please can we make these top banners look better.

**Comment by franznoel** [comment]
Fixed the top banner along with fixing the mainmenu.
