### ISSUE TITLE
Grey strip

### ISSUE THREAD

**Issue by MovieFund** [fritzdenim/pangMoves#9]
Inside the profile page:

![screen shot 2016-01-27 at 1 26 58 am](https://cloud.githubusercontent.com/assets/16911000/12609165/1766bc66-c495-11e5-807b-e45e41659b98.png)
Looking to create a dark grey stip background colour for this banner.

**Comment by franznoel** [comment]
Changed the background to dark gray in http://moviefund.com/profile/.

Added line: `background: #333333 !important; /* 1d1d1d */`
In selector: `.content .follow-holder`

<img width="1022" alt="screen shot 2016-01-28 at 12 12 22 am" src="https://cloud.githubusercontent.com/assets/464229/12638652/d82ffcbe-c553-11e5-9da7-69c6bc6aa276.png">
